import './globals.css'
import { Roboto_Flex as Roboto } from 'next/font/google'
import React from 'react'

const roboto = Roboto({ subsets: ['latin'] })

export const metadata = {
  title: 'TODO App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
